#!/bin/bash

set -e

BUILD_PARALLEL="-j1"

su -c "apt-get install bash bridge-utils ebtables iproute libev-dev python \
    tcl8.5 tk8.5 libtk-img \
    autoconf automake gcc libev-dev make libreadline-dev pkg-config \
    imagemagick help2man unionfs-fuse \
    python3 python3-dev quagga dnsmasq bind9" root

./bootstrap.sh
export PYTHON=python3; ./configure --prefix=/usr

make $BUILD_PARALLEL
su -c "make install" root

CORECFG="/etc/core"
mkdir -p "$CORECFG"
chmod -R 775 "$CORECFG"
addgroup core || echo "group \"core\" already exists. this can be ignored"
chgrp -R core "$CORECFG"

cp -v files/nodes.conf "$CORECFG/"
cp -v files/ipaddrs.conf "$CORECFG/"
cp -v files/widgets.conf "$CORECFG/"

echo "done. now for each user using core, create a symlink pointing from \"$HOME/.core\" -> \"$CORECFG\""

