#!/bin/bash

set -e

BUILD_PARALLEL="-j1"

su -c "apt-get install bash bridge-utils ebtables iproute libev-dev python \
    tcl8.5 tk8.5 libtk-img \
    autoconf automake gcc libev-dev make libreadline-dev pkg-config \
    imagemagick help2man \
    python3 python3-dev quagga" root

./bootstrap.sh
export PYTHON=python3; ./configure --prefix=/usr

make $BUILD_PARALLEL
su -c "make install" root

mkdir -p $HOME/.core
cp files/nodes.conf $HOME/.core/
